### ISSUE TITLE
Caption revisions (needs mockup)(has mockup)

### ISSUE THREAD

**Issue by MirandaEcho** [INN/theme-calhealthreport#13]
Delineate the photo captions from the text in the story and have a different text option for the photo credit.

INN Labs approach: If we increase the font size of article text, and leave the image caption text size unchanged, is that enough to delineate the photo caption from the text? Yes, client is open to different text size or font for the photo credit portion of the caption, as in the NYT example

**Comment by benlk** [comment]
Using https://www.calhealthreport.org/2020/05/19/this-crisis-has-led-to-more-equitable-policies-that-california-should-keep/ as an example of an article that doesn't have an istockphoto credit

caption font size remains 1rem/16px, entry content to 18px:

![Screen Shot 2020-05-20 at 18 26 45](https://user-images.githubusercontent.com/1754187/82503564-86dcad00-9ac7-11ea-8464-f6e1eeb11ade.png)

```css
/* foundation.css | https://www.calhealthreport.org/wp-content/themes/allonsy/assets/stylesheets/foundation.css?ver=2.6.1 */
.breadcrumbs span, body:not(.home) .entry-content a, body:not(.home) .entry-content li, body:not(.home) .entry-content p, body:not(.home) .entry-content span {
  /* font-size: 1rem !important; */
}
body.single .entry-content {
  font-size: 18px;
}

/* Inline #25 | https://www.calhealthreport.org/2020/05/19/this-crisis-has-led-to-more-equitable-policies-that-california-should-keep/ */
figcaption {
  font-size: 1rem;
}
```

Caption text made smaller:

![Screen Shot 2020-05-20 at 18 27 57](https://user-images.githubusercontent.com/1754187/82503638-ad9ae380-9ac7-11ea-8f59-fdaa2e4a77a4.png)

```css
/* foundation.css | https://www.calhealthreport.org/wp-content/themes/allonsy/assets/stylesheets/foundation.css?ver=2.6.1 */
.breadcrumbs span, body:not(.home) .entry-content a, body:not(.home) .entry-content li, body:not(.home) .entry-content p, body:not(.home) .entry-content span {
  /* font-size: 1rem !important; */
}
body.single .entry-content {
  font-size: 18px;
}

/* Inline #25 | https://www.calhealthreport.org/2020/05/19/this-crisis-has-led-to-more-equitable-policies-that-california-should-keep/ */
figcaption {
  font-size: 80%;
}
```

The captions are currently wrapped in an `<em>` tag to italicize them; we can make italics the default style for these so they don't need to be manually italicized.

**Comment by MirandaEcho** [comment]
This looks good, especially if we increase the body font further as noted in the other issue. I'll find out if she wants the default to be italicized or not.  It would be great to get a final mockup with the 20px font and italicized captions please. Thanks!

**Comment by benlk** [comment]
14px figcaption, 20px body:

![Screen Shot 2020-05-27 at 10 56 27](https://user-images.githubusercontent.com/1754187/83036551-bd0ab700-a008-11ea-8b5a-43d22441c7bc.png)

```css

/* foundation.css | https://www.calhealthreport.org/wp-content/themes/allonsy/assets/stylesheets/foundation.css?ver=2.6.1 */

.breadcrumbs span, body:not(.home) .entry-content a, body:not(.home) .entry-content li, body:not(.home) .entry-content p, body:not(.home) .entry-content span {
  /* font-size: 1rem !important; */
}

/* Inline #25 | https://www.calhealthreport.org/2020/05/19/this-crisis-has-led-to-more-equitable-policies-that-california-should-keep/ */

body.single .entry-content {
  font-size: 20px;
}

figcaption {
  font-size: 14px;
}

```
