### ISSUE TITLE
Notes upon making the main nav overlay the fullwidth header image

### ISSUE THREAD

**Issue by benlk** [INN/theme-calhealthreport#2]
Goal: something like https://www.nytimes.com/2020/04/01/us/la-county-coronavirus-hospitals.html

Using https://www.calhealthreport.org/2020/04/14/for-californians-without-water-access-coronavirus-adds-another-layer-of-struggle/ as an example mockup, here's a screenshot of the a modified page using https://github.com/mrmrs/pesticide to highlight elements:

![Screenshot_2020-05-01 For Californians Without Water Access, Coronavirus Adds Another Layer of Struggle](https://user-images.githubusercontent.com/1754187/80821057-0bfa3380-8ba6-11ea-8c7b-41d2547a53dd.jpg)

The headline and byline placement here is temporary, to get them out of the way of the nav.

nav is transparent, overlaid on the image.

Modifications from Firefox:
```css
/* Element | https://www.calhealthreport.org/2020/04/14/for-californians-without-water-access-coronavirus-adds-another-layer-of-struggle/ */
figure.wp-block-image.alignfull:nth-child(1) {
  width: 100vw;
  position: relative;
  left: calc( -50vw + 50% );
}

/* foundation.css | https://www.calhealthreport.org/wp-content/themes/allonsy/assets/stylesheets/foundation.css?ver=2.6.1 */

.entry-content, body.modal-active {
  /* overflow: hidden; */
}

header#masthead.header-option-two .top-bar.main-navigation {
  /* padding-top: 20px !important; */
  padding-top: 0;
}

/* Element | https://www.calhealthreport.org/2020/04/14/for-californians-without-water-access-coronavirus-adds-another-layer-of-struggle/ */

#masthead {
  position: fixed;
  background: transparent;
  top: 0;
  left: 0;
  z-index: 11;
  width: 100%;
}
```
